# Generated by Django 5.0.2 on 2026-02-16 11:32

from django.contrib.postgres.operations import CreateExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0011_remove_mediapost_research_use_allowed'),
    ]

    operations = [
        CreateExtension('postgis'),
    ]
