# Generated by Django 5.0.2 on 2026-02-16 11:32

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0012_enable_postgis_extension'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediapost',
            name='private_location_spatial',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='mediapost',
            name='public_location_spatial',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='mediapost',
            name='true_location_spatial',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
