# Generated by Django 5.0.2 on 2026-03-26 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("socialmedia", "0015_remove_obfuscation_box_and_redundant_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="mediapost",
            name="num_identification_agreements",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="mediapost",
            name="num_identification_disagreements",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="mediapost",
            name="quality_grade",
            field=models.CharField(
                choices=[
                    ("casual", "Casual"),
                    ("needs_id", "Needs ID"),
                    ("research", "Research"),
                ],
                default="casual",
                max_length=16,
            ),
        ),
    ]
