# Generated by Django 5.0.2 on 2026-03-26 15:31

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("socialmedia", "0016_mediapost_num_identification_agreements_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PostQualityMetric",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "metric",
                    models.CharField(
                        choices=[
                            ("wild", "Is the organism wild?"),
                            ("location", "Does the location seem accurate?"),
                            ("date", "Does the date seem accurate?"),
                            (
                                "evidence",
                                "Is there sufficient evidence of the organism?",
                            ),
                            ("species_id", "Does this match the identified species?"),
                        ],
                        max_length=16,
                    ),
                ),
                ("agree", models.BooleanField(default=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quality_metrics",
                        to="socialmedia.mediapost",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quality_metric_votes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("post", "user", "metric")},
            },
        ),
    ]
