# Generated by Django 5.0.2 on 2026-03-28 11:15

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("socialmedia", "0017_postqualitymetric"),
        ("species", "0002_alter_speciesname_scientific_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="mediapost",
            name="animal_count",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Number of individual animals in the sighting",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="SightingSpecies",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("rank", models.PositiveSmallIntegerField(default=1)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sighting_species",
                        to="socialmedia.mediapost",
                    ),
                ),
                (
                    "species",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="species.speciesname",
                    ),
                ),
            ],
            options={
                "ordering": ["rank"],
                "unique_together": {("post", "rank"), ("post", "species")},
            },
        ),
    ]
