# Generated by Django 5.0.2 on 2026-03-30 13:05

from django.db import migrations, models


def backfill_animal_count(apps, schema_editor):
    MediaPost = apps.get_model("socialmedia", "MediaPost")
    MediaPost.objects.filter(animal_count__isnull=True).update(animal_count=1)


class Migration(migrations.Migration):

    dependencies = [
        ("socialmedia", "0018_mediapost_animal_count_sightingspecies"),
    ]

    operations = [
        migrations.RunPython(backfill_animal_count, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="mediapost",
            name="animal_count",
            field=models.PositiveSmallIntegerField(
                default=1, help_text="Number of individual animals in the sighting"
            ),
        ),
    ]
