# Generated by Django 5.0.2 on 2026-04-02 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0019_alter_mediapost_animal_count'),
        ('species', '0003_taxon_taxonname'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sightingspecies',
            unique_together={('post', 'rank')},
        ),
        migrations.AddField(
            model_name='mediapost',
            name='taxon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_posts', to='species.taxon'),
        ),
        migrations.AddField(
            model_name='sightingspecies',
            name='taxon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sighting_species', to='species.taxon'),
        ),
        migrations.AlterField(
            model_name='sightingspecies',
            name='species',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='species.speciesname'),
        ),
    ]
