# Generated by Django 5.0.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("socialmedia", "0020_alter_sightingspecies_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mediapost",
            name="license_code",
            field=models.CharField(
                choices=[
                    ("cc0", "CC0 — Public Domain Dedication"),
                    ("cc-by", "CC BY — Attribution"),
                    ("cc-by-sa", "CC BY-SA — Attribution-ShareAlike"),
                    ("cc-by-nd", "CC BY-ND — Attribution-NoDerivatives"),
                    ("cc-by-nc", "CC BY-NC — Attribution-NonCommercial"),
                    ("cc-by-nc-sa", "CC BY-NC-SA — Attribution-NonCommercial-ShareAlike"),
                    ("cc-by-nc-nd", "CC BY-NC-ND — Attribution-NonCommercial-NoDerivatives"),
                    ("all-rights-reserved", "All Rights Reserved"),
                ],
                default="cc0",
                help_text="License for media and sighting data",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="mediapost",
            name="attribution_override",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Custom attribution name; leave blank to use poster's display name",
                max_length=256,
            ),
        ),
    ]
