# Generated by Django 5.0.2 on 2026-04-11 22:43

import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("socialmedia", "0022_mediapost_sighting_type_sightingmedia_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SightingType",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "code",
                    models.CharField(
                        help_text="Unique code identifier (e.g., 'live_sighting')",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        help_text="Display name (e.g., 'Live Sighting')", max_length=100
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional description of this sighting type",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveSmallIntegerField(
                        default=100, help_text="Order for display in dropdowns"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this type is available for selection",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sighting Type",
                "verbose_name_plural": "Sighting Types",
                "ordering": ["display_order", "display_name"],
            },
        ),
        migrations.AlterField(
            model_name="mediapost",
            name="sighting_type",
            field=models.CharField(
                choices=[
                    ("unknown", "Unknown/Not Specified"),
                    ("live_sighting", "Live Sighting"),
                    ("camera_trap", "Camera Trap"),
                    ("track_sign", "Track or Sign"),
                    ("killed", "Killed/Roadkill"),
                ],
                default="unknown",
                help_text="Type of sighting (live, camera trap, track/sign, etc.)",
                max_length=50,
            ),
        ),
    ]
