# Generated by Django 5.0.2 on 2026-04-11 22:43

from django.db import migrations


def populate_sighting_types(apps, schema_editor):
    """Create the default sighting types with specific IDs."""
    SightingType = apps.get_model("socialmedia", "SightingType")
    
    # Define the default sighting types with specific IDs
    default_types = [
        {
            "id": 1,
            "code": "unknown",
            "display_name": "Unknown/Not Specified",
            "description": "Sighting type not specified or unknown",
            "display_order": 100,
            "is_active": True,
        },
        {
            "id": 2,
            "code": "live_sighting",
            "display_name": "Live Sighting",
            "description": "Direct observation of a live animal",
            "display_order": 10,
            "is_active": True,
        },
        {
            "id": 3,
            "code": "camera_trap",
            "display_name": "Camera Trap",
            "description": "Animal captured by camera trap or trail camera",
            "display_order": 20,
            "is_active": True,
        },
        {
            "id": 4,
            "code": "track_sign",
            "display_name": "Track or Sign",
            "description": "Evidence of animal presence (tracks, scat, scratch marks, etc.)",
            "display_order": 30,
            "is_active": True,
        },
        {
            "id": 5,
            "code": "killed",
            "display_name": "Killed/Roadkill",
            "description": "Dead animal (roadkill, predation, etc.)",
            "display_order": 40,
            "is_active": True,
        },
    ]
    
    # Create each sighting type
    for type_data in default_types:
        SightingType.objects.create(**type_data)


def reverse_populate(apps, schema_editor):
    """Remove all sighting types."""
    SightingType = apps.get_model("socialmedia", "SightingType")
    SightingType.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("socialmedia", "0023_create_sighting_type_table"),
    ]

    operations = [
        migrations.RunPython(populate_sighting_types, reverse_populate),
    ]
