# Generated by Django 5.0.2 on 2026-04-11 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("socialmedia", "0024_populate_sighting_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="mediapost",
            name="sighting_type_fk",
            field=models.ForeignKey(
                blank=True,
                help_text="Type of sighting (FK to SightingType model)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="posts",
                to="socialmedia.sightingtype",
            ),
        ),
    ]
