# Generated by Django 5.0.2 on 2026-04-11 22:44

from django.db import migrations


def migrate_sighting_type_data(apps, schema_editor):
    """Migrate data from sighting_type CharField to sighting_type_fk FK."""
    MediaPost = apps.get_model("socialmedia", "MediaPost")
    SightingType = apps.get_model("socialmedia", "SightingType")
    
    # Create mapping from code to SightingType ID
    code_to_type = {st.code: st for st in SightingType.objects.all()}
    
    # Update all MediaPost records
    for post in MediaPost.objects.all():
        if post.sighting_type and post.sighting_type in code_to_type:
            post.sighting_type_fk = code_to_type[post.sighting_type]
            post.save(update_fields=["sighting_type_fk"])


def reverse_migrate(apps, schema_editor):
    """Reverse migration - copy FK back to CharField."""
    MediaPost = apps.get_model("socialmedia", "MediaPost")
    
    for post in MediaPost.objects.all():
        if post.sighting_type_fk:
            post.sighting_type = post.sighting_type_fk.code
            post.save(update_fields=["sighting_type"])


class Migration(migrations.Migration):

    dependencies = [
        ("socialmedia", "0025_add_sighting_type_fk"),
    ]

    operations = [
        migrations.RunPython(migrate_sighting_type_data, reverse_migrate),
    ]
