# Generated by Django 5.0.2 on 2026-04-11 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("socialmedia", "0026_migrate_sighting_type_data"),
    ]

    operations = [
        # First, remove the old CharField
        migrations.RemoveField(
            model_name="mediapost",
            name="sighting_type",
        ),
        # Then rename the FK field
        migrations.RenameField(
            model_name="mediapost",
            old_name="sighting_type_fk",
            new_name="sighting_type",
        ),
    ]
