# Generated by Django 5.0.2 on 2026-04-12 11:42

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("socialmedia", "0027_finalize_sighting_type_fk"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteConfiguration",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "max_sighting_images",
                    models.PositiveSmallIntegerField(
                        default=5,
                        help_text="Maximum number of images that can be attached to a single sighting",
                    ),
                ),
            ],
            options={
                "verbose_name": "Site Configuration",
                "verbose_name_plural": "Site Configuration",
            },
        ),
        migrations.AlterField(
            model_name="mediapost",
            name="sighting_type",
            field=models.ForeignKey(
                blank=True,
                help_text="Type of sighting (live, camera trap, track/sign, etc.)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="posts",
                to="socialmedia.sightingtype",
            ),
        ),
    ]
