# Generated by Django 5.0.2 on 2026-04-12 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("socialmedia", "0028_siteconfiguration_alter_mediapost_sighting_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="mediapost",
            name="iucn_habitat_lvl1_code",
            field=models.IntegerField(
                blank=True,
                help_text="IUCN Level 1 habitat classification code (e.g., 400=Temperate Forest, 1400=Wetlands)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="mediapost",
            name="iucn_habitat_lvl1_name",
            field=models.CharField(
                blank=True,
                help_text="Human-readable name for Level 1 habitat classification",
                max_length=128,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="mediapost",
            name="iucn_habitat_lvl2_code",
            field=models.IntegerField(
                blank=True,
                help_text="IUCN Level 2 habitat classification code (more granular than Level 1)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="mediapost",
            name="iucn_habitat_lvl2_name",
            field=models.CharField(
                blank=True,
                help_text="Human-readable name for Level 2 habitat classification",
                max_length=128,
                null=True,
            ),
        ),
    ]
