# Generated by Django 5.0.2 on 2026-04-13 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("socialmedia", "0029_mediapost_iucn_habitat_lvl1_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="habitat_classification_level",
            field=models.CharField(
                choices=[
                    ("level1", "Level 1 (Broad classification)"),
                    ("level2", "Level 2 (Detailed classification)"),
                ],
                default="level1",
                help_text="Which IUCN habitat classification level to use for automatic habitat lookup",
                max_length=10,
            ),
        ),
    ]
