# Generated by Django 5.0.2 on 2026-04-13 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("socialmedia", "0030_siteconfiguration_habitat_classification_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="mediapost",
            name="iucn_habitat_level_used",
            field=models.CharField(
                blank=True,
                choices=[("level1", "Level 1"), ("level2", "Level 2")],
                help_text="Tracks which IUCN habitat level was used when this sighting's habitat was last updated",
                max_length=10,
                null=True,
            ),
        ),
    ]
