# Generated by Django 5.0.2 on 2026-04-13 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("socialmedia", "0031_mediapost_iucn_habitat_level_used"),
    ]

    operations = [
        migrations.CreateModel(
            name="IUCNHabitatClassification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[("level1", "Level 1"), ("level2", "Level 2")],
                        help_text="Classification level (broad or detailed)",
                        max_length=10,
                    ),
                ),
                (
                    "code",
                    models.IntegerField(
                        help_text="IUCN numeric habitat code (e.g., 100=Forest, 400=Grassland)"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable habitat name", max_length=128
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional detailed description of this habitat type",
                    ),
                ),
            ],
            options={
                "verbose_name": "IUCN Habitat Classification",
                "verbose_name_plural": "IUCN Habitat Classifications",
                "ordering": ["level", "code"],
                "indexes": [
                    models.Index(
                        fields=["level", "code"], name="socialmedia_level_37a13e_idx"
                    )
                ],
                "unique_together": {("level", "code")},
            },
        ),
    ]
