# Generated by Django 5.0.2 on 2026-04-13 12:16

from django.db import migrations


def populate_iucn_habitat_classifications(apps, schema_editor):
    """Populate IUCN habitat classification lookup table with official codes and names."""
    IUCNHabitatClassification = apps.get_model("socialmedia", "IUCNHabitatClassification")
    
    # Level 1 habitat classifications (broad categories)
    level1_data = {
        0: "Water",
        100: "Forest",
        200: "Savanna",
        300: "Shrubland",
        400: "Grassland",
        500: "Wetlands (inland)",
        600: "Rocky Areas",
        800: "Desert",
        1400: "Artificial - Terrestrial",
        1700: "Unknown",
    }
    
    # Level 2 habitat classifications (detailed categories)
    level2_data = {
        0: "Water",
        100: "Forest",
        101: "Forest - Boreal",
        102: "Forest - Subarctic",
        103: "Forest - Subantarctic",
        104: "Forest - Temperate",
        105: "Forest - Subtropical-tropical dry",
        106: "Forest - Subtropical-tropical moist lowland",
        107: "Forest - Subtropical-tropical mangrove vegetation",
        108: "Forest - Subtropical-tropical swamp",
        109: "Forest - Subtropical-tropical moist montane",
        200: "Savanna",
        201: "Savanna - Dry",
        202: "Savanna - Moist",
        300: "Shrubland",
        301: "Shrubland - Subarctic",
        302: "Shrubland - Subantarctic",
        303: "Shrubland - Boreal",
        304: "Shrubland - Temperate",
        305: "Shrubland - Subtropical-tropical dry",
        306: "Shrubland - Subtropical-tropical moist",
        307: "Shrubland - Subtropical-tropical high altitude",
        308: "Shrubland - Mediterranean-type",
        400: "Grassland",
        401: "Grassland - Tundra",
        402: "Grassland - Subarctic",
        403: "Grassland - Subantarctic",
        404: "Grassland - Temperate",
        405: "Grassland - Subtropical-tropical dry",
        406: "Grassland - Subtropical-tropical seasonally wet or flooded",
        407: "Grassland - Subtropical-tropical high altitude",
        500: "Wetlands (inland)",
        501: "Wetlands (inland) - Permanent rivers streams creeks",
        502: "Wetlands (inland) - Seasonal/intermittent/irregular rivers/streams/creeks",
        503: "Wetlands (inland) - Shrub dominated wetlands",
        504: "Wetlands (inland) - Bogs/marshes/swamps/fens/peatlands",
        505: "Wetlands (inland) - Permanent freshwater lakes",
        506: "Wetlands (inland) - Seasonal/intermittent freshwater lakes (over 8 ha)",
        507: "Wetlands (inland) - Permanent freshwater marshes/pools (under 8 ha)",
        508: "Wetlands (inland) - Seasonal/intermittent freshwater marshes/pools (under 8 ha)",
        509: "Wetlands (inland) - Freshwater springs and oases",
        510: "Wetlands (inland) - Tundra wetlands",
        511: "Wetlands (inland) - Alpine wetlands",
        512: "Wetlands (inland) - Geothermal wetlands",
        513: "Wetlands (inland) - Permanent inland deltas",
        514: "Wetlands (inland) - Permanent saline brackish or alkaline lakes",
        515: "Wetlands (inland) - Seasonal/intermittent saline brackish or alkaline lakes and flats",
        516: "Wetlands (inland) - Permanent /saline / brackish or alkaline marshes/pools",
        517: "Wetlands (inland) - Seasonal/intermittent /saline / brackish or alkaline marshes/pools",
        518: "Wetlands (inland) / Karst and other subterranean hydrological systems",
        600: "Rocky Areas",
        800: "Desert",
        801: "Desert - Hot",
        802: "Desert - Temperate",
        803: "Desert - Cold",
        1400: "Artificial - Terrestrial",
        1401: "Arable land",
        1402: "Pastureland",
        1403: "Plantations",
        1404: "Rural Gardens",
        1405: "Urban Areas",
        1406: "Subtropical/Tropical Heavily Degraded Former Forest",
        1700: "Unknown",
    }
    
    # Create Level 1 records
    for code, name in level1_data.items():
        IUCNHabitatClassification.objects.create(
            level="level1",
            code=code,
            name=name
        )
    
    # Create Level 2 records
    for code, name in level2_data.items():
        IUCNHabitatClassification.objects.create(
            level="level2",
            code=code,
            name=name
        )


def reverse_populate(apps, schema_editor):
    """Delete all IUCN habitat classification records."""
    IUCNHabitatClassification = apps.get_model("socialmedia", "IUCNHabitatClassification")
    IUCNHabitatClassification.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("socialmedia", "0032_iucnhabitatclassification"),
    ]

    operations = [
        migrations.RunPython(populate_iucn_habitat_classifications, reverse_populate),
    ]
