# Generated by Django 5.0.2 on 2026-04-13 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("socialmedia", "0033_populate_iucn_habitat_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="mediapost",
            name="iucn_habitat_lvl1",
            field=models.ForeignKey(
                blank=True,
                help_text="Level 1 IUCN habitat classification (broad categories)",
                limit_choices_to={"level": "level1"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="media_posts_lvl1",
                to="socialmedia.iucnhabitatclassification",
            ),
        ),
        migrations.AddField(
            model_name="mediapost",
            name="iucn_habitat_lvl2",
            field=models.ForeignKey(
                blank=True,
                help_text="Level 2 IUCN habitat classification (detailed categories)",
                limit_choices_to={"level": "level2"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="media_posts_lvl2",
                to="socialmedia.iucnhabitatclassification",
            ),
        ),
        migrations.AlterField(
            model_name="mediapost",
            name="iucn_habitat_lvl1_name",
            field=models.CharField(
                blank=True,
                help_text="DEPRECATED: Use iucn_habitat_lvl1 FK instead. Human-readable name for Level 1 habitat classification",
                max_length=128,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="mediapost",
            name="iucn_habitat_lvl2_name",
            field=models.CharField(
                blank=True,
                help_text="DEPRECATED: Use iucn_habitat_lvl2 FK instead. Human-readable name for Level 2 habitat classification",
                max_length=128,
                null=True,
            ),
        ),
    ]
