# Generated by Django 5.0.2 on 2026-04-13 12:18

from django.db import migrations


def populate_habitat_fks(apps, schema_editor):
    """Populate IUCN habitat FK fields from existing code fields."""
    MediaPost = apps.get_model("socialmedia", "MediaPost")
    IUCNHabitatClassification = apps.get_model("socialmedia", "IUCNHabitatClassification")
    
    # Build lookup dictionaries for efficient FK assignment
    lvl1_lookup = {
        habitat.code: habitat 
        for habitat in IUCNHabitatClassification.objects.filter(level="level1")
    }
    lvl2_lookup = {
        habitat.code: habitat 
        for habitat in IUCNHabitatClassification.objects.filter(level="level2")
    }
    
    # Process posts in batches for memory efficiency
    batch_size = 1000
    updated_count = 0
    
    # Update Level 1 habitat FKs
    for post in MediaPost.objects.filter(iucn_habitat_lvl1_code__isnull=False).iterator(chunk_size=batch_size):
        if post.iucn_habitat_lvl1_code in lvl1_lookup:
            post.iucn_habitat_lvl1 = lvl1_lookup[post.iucn_habitat_lvl1_code]
            post.save(update_fields=["iucn_habitat_lvl1"])
            updated_count += 1
    
    # Update Level 2 habitat FKs
    for post in MediaPost.objects.filter(iucn_habitat_lvl2_code__isnull=False).iterator(chunk_size=batch_size):
        if post.iucn_habitat_lvl2_code in lvl2_lookup:
            post.iucn_habitat_lvl2 = lvl2_lookup[post.iucn_habitat_lvl2_code]
            post.save(update_fields=["iucn_habitat_lvl2"])
            updated_count += 1
    
    print(f"Updated {updated_count} MediaPost records with IUCN habitat FKs")


def reverse_populate(apps, schema_editor):
    """Clear IUCN habitat FK fields."""
    MediaPost = apps.get_model("socialmedia", "MediaPost")
    MediaPost.objects.update(iucn_habitat_lvl1=None, iucn_habitat_lvl2=None)


class Migration(migrations.Migration):

    dependencies = [
        ("socialmedia", "0034_mediapost_iucn_habitat_lvl1_and_more"),
    ]

    operations = [
        migrations.RunPython(populate_habitat_fks, reverse_populate),
    ]
