# Generated by Django 5.0.2 on 2026-04-13 12:46

import logging
from django.db import migrations

logger = logging.getLogger(__name__)


def backfill_habitat_codes(apps, schema_editor):
    """
    Backfill IUCN habitat codes (both Level 1 and Level 2) for all existing MediaPost
    sightings that have a location but missing habitat data.
    """
    MediaPost = apps.get_model("socialmedia", "MediaPost")
    IUCNHabitatClassification = apps.get_model("socialmedia", "IUCNHabitatClassification")
    
    from siteapps.socialmedia.iucn_habitat_utils import get_iucn_habitat_codes
    
    # Find sightings with valid coordinates but missing BOTH habitat codes
    posts_to_update = MediaPost.objects.filter(
        true_location_spatial__isnull=False,
        iucn_habitat_lvl1_code__isnull=True,
        iucn_habitat_lvl2_code__isnull=True,
    )
    
    total = posts_to_update.count()
    logger.info(f"Found {total} sightings to backfill with IUCN habitat codes")
    print(f"\nBackfilling IUCN habitat codes for {total} sightings...")
    
    updated_count = 0
    error_count = 0
    batch_size = 100
    
    for i, post in enumerate(posts_to_update.iterator(chunk_size=batch_size), 1):
        try:
            # Extract latitude and longitude from Point geometry
            latitude = post.true_location_spatial.y
            longitude = post.true_location_spatial.x
            
            # Get habitat data for both levels
            habitat_data = get_iucn_habitat_codes(latitude, longitude)
            
            if habitat_data:
                lvl1_code = habitat_data.get("iucn_habitat_lvl1_code")
                lvl2_code = habitat_data.get("iucn_habitat_lvl2_code")
                
                # Update integer codes and names (for backward compatibility)
                post.iucn_habitat_lvl1_code = lvl1_code
                post.iucn_habitat_lvl1_name = habitat_data.get("iucn_habitat_lvl1_name")
                post.iucn_habitat_lvl2_code = lvl2_code
                post.iucn_habitat_lvl2_name = habitat_data.get("iucn_habitat_lvl2_name")
                
                # Set FK relationships if classification records exist
                if lvl1_code is not None:
                    try:
                        post.iucn_habitat_lvl1 = IUCNHabitatClassification.objects.get(
                            code=lvl1_code, level="level1"
                        )
                    except IUCNHabitatClassification.DoesNotExist:
                        logger.warning(f"No IUCNHabitatClassification found for level1 code {lvl1_code}")
                        post.iucn_habitat_lvl1 = None
                
                if lvl2_code is not None:
                    try:
                        post.iucn_habitat_lvl2 = IUCNHabitatClassification.objects.get(
                            code=lvl2_code, level="level2"
                        )
                    except IUCNHabitatClassification.DoesNotExist:
                        logger.warning(f"No IUCNHabitatClassification found for level2 code {lvl2_code}")
                        post.iucn_habitat_lvl2 = None
                
                post.save(update_fields=[
                    'iucn_habitat_lvl1_code', 'iucn_habitat_lvl1_name', 'iucn_habitat_lvl1',
                    'iucn_habitat_lvl2_code', 'iucn_habitat_lvl2_name', 'iucn_habitat_lvl2'
                ])
                updated_count += 1
                
                if i % batch_size == 0:
                    logger.info(f"Processed {i}/{total} sightings...")
                    print(f"Progress: {i}/{total} sightings processed ({updated_count} updated, {error_count} errors)")
                    
        except Exception as e:
            error_count += 1
            logger.error(f"Error updating post {post.id}: {str(e)}")
    
    logger.info(f"Backfill complete: {updated_count} updated, {error_count} errors out of {total} total")
    print(f"\nBackfill complete: {updated_count} sightings updated, {error_count} errors")


def reverse_backfill(apps, schema_editor):
    """
    Reverse migration - clear habitat codes that were set by backfill.
    Note: This cannot perfectly distinguish between backfilled data and
    data set during normal operation, so we only clear codes without FKs.
    """
    MediaPost = apps.get_model("socialmedia", "MediaPost")
    
    # Only clear codes that don't have FK relationships (likely backfilled)
    posts_to_clear = MediaPost.objects.filter(
        iucn_habitat_lvl1_code__isnull=False,
        iucn_habitat_lvl1__isnull=True,
    ) | MediaPost.objects.filter(
        iucn_habitat_lvl2_code__isnull=False,
        iucn_habitat_lvl2__isnull=True,
    )
    
    count = posts_to_clear.count()
    print(f"\nClearing habitat codes from {count} sightings...")
    
    for post in posts_to_clear.iterator():
        post.iucn_habitat_lvl1_code = None
        post.iucn_habitat_lvl1_name = None
        post.iucn_habitat_lvl1 = None
        post.iucn_habitat_lvl2_code = None
        post.iucn_habitat_lvl2_name = None
        post.iucn_habitat_lvl2 = None
        post.save(update_fields=[
            'iucn_habitat_lvl1_code', 'iucn_habitat_lvl1_name', 'iucn_habitat_lvl1',
            'iucn_habitat_lvl2_code', 'iucn_habitat_lvl2_name', 'iucn_habitat_lvl2'
        ])
    
    print(f"Cleared habitat codes from {count} sightings")


class Migration(migrations.Migration):

    dependencies = [
        ("socialmedia", "0035_populate_habitat_fks_from_codes"),
    ]

    operations = [
        migrations.RunPython(backfill_habitat_codes, reverse_backfill),
    ]

