# Generated by Django 5.0.2 on 2026-04-13 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("socialmedia", "0036_backfill_habitat_codes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mediapost",
            name="iucn_habitat_level_used",
        ),
        migrations.RemoveField(
            model_name="mediapost",
            name="iucn_habitat_lvl1_code",
        ),
        migrations.RemoveField(
            model_name="mediapost",
            name="iucn_habitat_lvl1_name",
        ),
        migrations.RemoveField(
            model_name="mediapost",
            name="iucn_habitat_lvl2_code",
        ),
        migrations.RemoveField(
            model_name="mediapost",
            name="iucn_habitat_lvl2_name",
        ),
    ]
