# Generated by Django 5.0.2 on 2026-04-29 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("socialmedia", "0037_remove_mediapost_iucn_habitat_level_used_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersightinglocation",
            name="camera_deployment_date",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="usersightinglocation",
            name="camera_model",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="usersightinglocation",
            name="camera_serial_number",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="usersightinglocation",
            name="camera_timestamp_offset_error_details",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
