# Generated by Django 5.0.2 on 2026-05-07 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("socialmedia", "0040_bulkuploadsession"),
    ]

    operations = [
        migrations.AddField(
            model_name="bulkuploadsession",
            name="bird_calls",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
