# Generated by Django 5.0.2 on 2026-07-20 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("socialmedia", "0041_bulkuploadsession_bird_calls"),
    ]

    operations = [
        migrations.AddField(
            model_name="mediapost",
            name="device_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("camera", "Camera"),
                    ("phone", "Phone"),
                    ("home_camera", "Home Camera"),
                    ("trail_camera", "Trail Camera"),
                ],
                max_length=16,
                null=True,
            ),
        ),
    ]
