@echo off
setlocal enabledelayedexpansion

echo Setting up Wilde Backyard Backend with uv...
echo.

:: Install uv if not already installed
where uv >nul 2>&1
if %ERRORLEVEL% NEQ 0 (
    echo Installing uv...
    powershell -c "irm https://astral.sh/uv/install.ps1 | iex"
)

:: Create virtual environment using uv
echo Creating virtual environment...
uv venv

:: Activate virtual environment
echo Activating virtual environment...
call .venv\Scripts\activate.bat

:: Install dependencies
echo Installing dependencies...
uv pip install -e .

:: Change to the Django migrations directory and delete old migration files
echo Fixing django-rest-passwordreset migrations...
cd .venv\Lib\site-packages\django_rest_passwordreset\migrations
del 000*.py

:: Define the output file
set "output_file=0001_initial.py"

:: Create or overwrite the file with the specified content
(
    echo # Generated by Django 5.0.2 on 2024-05-07 18:40
    echo.
    echo import django.db.models.deletion
    echo from django.conf import settings
    echo from django.db import migrations, models
    echo.
    echo.
    echo class Migration^(migrations.Migration^):
    echo.
    echo     initial = True
    echo.
    echo     dependencies = [
    echo         migrations.swappable_dependency^(settings.AUTH_USER_MODEL^),
    echo     ]
    echo.
    echo     operations = [
    echo         migrations.CreateModel^(
    echo             name=^'ResetPasswordToken^',
    echo             fields=[
    echo                 ^(^'id^', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name=^'ID^'^)^),
    echo                 ^(^'created_at^', models.DateTimeField(auto_now_add=True, verbose_name=^'When was this token generated^'^)^),
    echo                 ^(^'key^', models.CharField(db_index=True, max_length=64, unique=True, verbose_name=^'Key^'^)^),
    echo                 ^(^'ip_address^', models.GenericIPAddressField(blank=True, default=^'^', null=True, verbose_name=^'The IP address of this session'^)^),
    echo                 ^(^'user_agent^', models.CharField(blank=True, default=^'^', max_length=512, verbose_name=^'HTTP User Agent^'^)^),
    echo                 ^(^'user^', models.ForeignKey^(on_delete=django.db.models.deletion.CASCADE, related_name=^'password_reset_tokens^', to=settings.AUTH_USER_MODEL, verbose_name=^'The User which is associated to this password reset token^'^)^),
    echo             ],
    echo             options={
    echo                 ^'verbose_name^': ^'Password Reset Token^',
    echo                 ^'verbose_name_plural': ^'Password Reset Tokens^',
    echo             },
    echo         ^),
    echo     ]
) > "%output_file%"

cd %~dp0

:: Confirm the file creation
if exist ".venv\Lib\site-packages\django_rest_passwordreset\migrations\%output_file%" (
    echo %output_file% has been created successfully.
) else (
    echo Failed to create %output_file%.
    pause
    exit /b 1
)

echo.
echo Setup complete!
echo.
echo To activate the environment in the future, run:
echo   .venv\Scripts\activate.bat
echo.
echo To run migrations:
echo   python manage.py migrate --settings=config.settings.local
echo.
echo To start the development server:
echo   python manage.py runserver --settings=config.settings.local
echo.

:: Pause to keep the command window open
pause
