@echo off
setlocal enabledelayedexpansion

:: Create a Python virtual environment and activate it
python -m venv venv
call venv\Scripts\activate.bat

:: Install requirements
pip install -r requirements.txt

:: Change to the Django migrations directory and delete old migration files
cd venv\Lib\site-packages\django_rest_passwordreset\migrations
del 000*.py

:: Define the output file
set "output_file=0001_initial.py"

:: Create or overwrite the file with the specified content
(
    echo # Generated by Django 5.0.2 on 2024-05-07 18:40
    echo.
    echo import django.db.models.deletion
    echo from django.conf import settings
    echo from django.db import migrations, models
    echo.
    echo.
    echo class Migration^(migrations.Migration^):
    echo.
    echo     initial = True
    echo.
    echo     dependencies = [
    echo         migrations.swappable_dependency^(settings.AUTH_USER_MODEL^),
    echo     ]
    echo.
    echo     operations = [
    echo         migrations.CreateModel^(
    echo             name=^'ResetPasswordToken^',
    echo             fields=[
    echo                 ^(^'id^', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name=^'ID^'^)^),
    echo                 ^(^'created_at^', models.DateTimeField(auto_now_add=True, verbose_name=^'When was this token generated^'^)^),
    echo                 ^(^'key^', models.CharField(db_index=True, max_length=64, unique=True, verbose_name=^'Key^'^)^),
    echo                 ^(^'ip_address^', models.GenericIPAddressField(blank=True, default=^'^', null=True, verbose_name=^'The IP address of this session'^)^),
    echo                 ^(^'user_agent^', models.CharField(blank=True, default=^'^', max_length=512, verbose_name=^'HTTP User Agent^'^)^),
    echo                 ^(^'user^', models.ForeignKey^(on_delete=django.db.models.deletion.CASCADE, related_name=^'password_reset_tokens^', to=settings.AUTH_USER_MODEL, verbose_name=^'The User which is associated to this password reset token^'^)^),
    echo             ],
    echo             options={
    echo                 ^'verbose_name^': ^'Password Reset Token^',
    echo                 ^'verbose_name_plural': ^'Password Reset Tokens^',
    echo             },
    echo         ^),
    echo     ]
) > "%output_file%"
:: Confirm the file creation
if exist "%output_file%" (
    echo %output_file% has been created with the specified content.
) else (
    echo Failed to create %output_file%.
)

:: Pause to keep the command window open
pause
