# Generated by Django 5.0.2 on 2026-04-11 23:29

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Admin1Code",
            fields=[
                (
                    "code",
                    models.CharField(
                        help_text="Country.AdminCode (e.g., US.CA)",
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Full name of state/province", max_length=200
                    ),
                ),
                (
                    "name_ascii",
                    models.CharField(help_text="ASCII version of name", max_length=200),
                ),
                (
                    "geonameid",
                    models.IntegerField(
                        blank=True,
                        help_text="GeoNames ID for this admin division",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Admin1 Code",
                "verbose_name_plural": "Admin1 Codes",
                "db_table": "admin1_codes",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="FeatureCode",
            fields=[
                (
                    "code",
                    models.CharField(
                        help_text="Feature code (e.g., PPL, ADM1)",
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, help_text="Short name of feature type", max_length=200, null=True
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Detailed description of feature type", null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Feature Code",
                "verbose_name_plural": "Feature Codes",
                "db_table": "feature_codes",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="GeoName",
            fields=[
                (
                    "geonameid",
                    models.IntegerField(
                        help_text="Unique GeoNames identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, help_text="Name in UTF-8 format", max_length=200, null=True),
                ),
                (
                    "asciiname",
                    models.CharField(
                        blank=True, help_text="Name in ASCII characters", max_length=200, null=True
                    ),
                ),
                (
                    "alternatenames",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated alternate names",
                        max_length=10000,
                        null=True,
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        help_text="Latitude in decimal degrees",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        help_text="Longitude in decimal degrees",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "fclass",
                    models.CharField(
                        blank=True,
                        help_text="Feature class (A=admin, P=populated place, H=water, etc)",
                        max_length=1,
                        null=True,
                    ),
                ),
                (
                    "fcode",
                    models.CharField(
                        blank=True,
                        help_text="Feature code (detailed classification)",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, help_text="ISO-3166 2-letter country code", max_length=2, null=True
                    ),
                ),
                (
                    "cc2",
                    models.CharField(
                        blank=True, help_text="Alternate country codes", max_length=200, null=True
                    ),
                ),
                (
                    "admin1",
                    models.CharField(
                        blank=True,
                        help_text="State/province code (FIPS)",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "admin2",
                    models.CharField(
                        blank=True,
                        help_text="County/second-level admin code",
                        max_length=80,
                        null=True,
                    ),
                ),
                (
                    "admin3",
                    models.CharField(
                        blank=True, help_text="Third-level admin code", max_length=20, null=True
                    ),
                ),
                (
                    "admin4",
                    models.CharField(
                        blank=True, help_text="Fourth-level admin code", max_length=20, null=True
                    ),
                ),
                (
                    "population",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Population (0 if not applicable)",
                        null=True,
                    ),
                ),
                (
                    "elevation",
                    models.IntegerField(
                        blank=True, help_text="Elevation in meters", null=True
                    ),
                ),
                (
                    "gtopo30",
                    models.IntegerField(
                        blank=True,
                        help_text="Average elevation from GTOPO30",
                        null=True,
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        blank=True,
                        help_text="Timezone (e.g., America/Los_Angeles)",
                        max_length=40,
                        null=True,
                    ),
                ),
                (
                    "moddate",
                    models.DateField(blank=True, help_text="Date of last modification", null=True),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, help_text="PostGIS Point geometry (WGS84)", null=True, srid=4326
                    ),
                ),
            ],
            options={
                "verbose_name": "GeoName",
                "verbose_name_plural": "GeoNames",
                "db_table": "geonames",
                "ordering": ["-population", "name"],
                "indexes": [
                    models.Index(fields=["name"], name="geonames_name_a43510_idx"),
                    models.Index(
                        fields=["country"], name="geonames_country_406fbf_idx"
                    ),
                    models.Index(fields=["admin1"], name="geonames_admin1_f49723_idx"),
                    models.Index(fields=["fcode"], name="geonames_fcode_548aaa_idx"),
                    models.Index(
                        fields=["-population"], name="geonames_populat_eac38d_idx"
                    ),
                    models.Index(
                        fields=["country", "admin1"], name="geonames_country_1146f6_idx"
                    ),
                    models.Index(
                        fields=["country", "fcode"], name="geonames_country_6ff8f8_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PostalCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        help_text="ISO-3166 2-letter country code (US or CA)",
                        max_length=2,
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        help_text="Postal code (ZIP for US, postal code for CA)",
                        max_length=20,
                    ),
                ),
                (
                    "place_name",
                    models.CharField(
                        blank=True,
                        help_text="Place name associated with postal code",
                        max_length=180,
                        null=True,
                    ),
                ),
                (
                    "admin1_name",
                    models.CharField(
                        blank=True, help_text="State/province name", max_length=100, null=True
                    ),
                ),
                (
                    "admin1_code",
                    models.CharField(
                        blank=True, help_text="State/province code", max_length=20, null=True
                    ),
                ),
                (
                    "admin2_name",
                    models.CharField(
                        blank=True, help_text="County/district name", max_length=100, null=True
                    ),
                ),
                (
                    "admin2_code",
                    models.CharField(
                        blank=True, help_text="County/district code", max_length=20, null=True
                    ),
                ),
                (
                    "admin3_name",
                    models.CharField(
                        blank=True, help_text="Community name", max_length=100, null=True
                    ),
                ),
                (
                    "admin3_code",
                    models.CharField(
                        blank=True, help_text="Community code", max_length=20, null=True
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        decimal_places=7,
                        help_text="Latitude of centroid",
                        max_digits=10,
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        decimal_places=7,
                        help_text="Longitude of centroid",
                        max_digits=10,
                    ),
                ),
                (
                    "accuracy",
                    models.SmallIntegerField(
                        blank=True,
                        help_text="Accuracy of coordinates (1-6, lower is better)",
                        null=True,
                    ),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True,
                        help_text="PostGIS Point geometry for centroid (WGS84)",
                        null=True,
                        srid=4326,
                    ),
                ),
            ],
            options={
                "verbose_name": "Postal Code",
                "verbose_name_plural": "Postal Codes",
                "db_table": "postal_codes",
                "ordering": ["country", "postal_code"],
                "indexes": [
                    models.Index(
                        fields=["country", "postal_code"],
                        name="postal_code_country_8f0e00_idx",
                    ),
                    models.Index(
                        fields=["postal_code"], name="postal_code_postal__29a4fe_idx"
                    ),
                    models.Index(
                        fields=["country", "admin1_code"],
                        name="postal_code_country_38d475_idx",
                    ),
                    models.Index(
                        fields=["place_name"], name="postal_code_place_n_c5375c_idx"
                    ),
                ],
            },
        ),
    ]
