# Generated by Django 5.0.2 on 2024-03-25 23:54

from django.db import migrations, models

import siteapps.users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_historicaluser_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='name',
            field=models.CharField(default=siteapps.users.models.generate_random_name, max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default=siteapps.users.models.generate_random_name, max_length=255, verbose_name='Name'),
        ),
    ]
