# Generated by Django 5.0.2 on 2024-07-01 19:47

import uuid

import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_historicaluser_name_alter_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannedEmail',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='historicaluser',
            name='location_latitude',
        ),
        migrations.RemoveField(
            model_name='historicaluser',
            name='location_longitude',
        ),
        migrations.RemoveField(
            model_name='historicaluser',
            name='zipcode',
        ),
        migrations.RemoveField(
            model_name='user',
            name='location_latitude',
        ),
        migrations.RemoveField(
            model_name='user',
            name='location_longitude',
        ),
        migrations.RemoveField(
            model_name='user',
            name='zipcode',
        ),
    ]
