# Generated by Django 5.0.2 on 2024-07-01 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_bannedemail_remove_historicaluser_location_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='warnings',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='warnings',
            field=models.IntegerField(default=0),
        ),
    ]
