# Generated by Django 5.0.2 on 2024-07-02 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_historicaluser_warnings_user_warnings'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannedemail',
            name='ban_reason',
            field=models.CharField(default='', max_length=800),
        ),
    ]
