# Generated by Django 5.0.2 on 2026-01-28 11:57

import siteapps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_bannedemail_ban_reason"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", siteapps.users.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name="historicaluser",
            name="bio",
            field=models.CharField(default="", max_length=10000, verbose_name="Bio"),
        ),
        migrations.AddField(
            model_name="user",
            name="bio",
            field=models.CharField(default="", max_length=10000, verbose_name="Bio"),
        ),
    ]
