# Generated by Django 5.0.2 on 2026-03-30 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_user_managers_historicaluser_bio_user_bio"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaluser",
            name="is_expert",
            field=models.BooleanField(
                default=False,
                help_text="Expert user votes directly validate Category, Species and Activity without need for additional consensus",
            ),
        ),
        migrations.AddField(
            model_name="historicaluser",
            name="is_volunteer",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicaluser",
            name="phone_number",
            field=models.CharField(
                blank=True, max_length=25, verbose_name="Phone Number"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_expert",
            field=models.BooleanField(
                default=False,
                help_text="Expert user votes directly validate Category, Species and Activity without need for additional consensus",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_volunteer",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True, max_length=25, verbose_name="Phone Number"
            ),
        ),
    ]
