# Generated by Django 5.0.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_add_volunteer_expert_phone_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaluser",
            name="default_license",
            field=models.CharField(
                choices=[
                    ("cc0", "CC0 — Public Domain Dedication"),
                    ("cc-by", "CC BY — Attribution"),
                    ("cc-by-sa", "CC BY-SA — Attribution-ShareAlike"),
                    ("cc-by-nd", "CC BY-ND — Attribution-NoDerivatives"),
                    ("cc-by-nc", "CC BY-NC — Attribution-NonCommercial"),
                    ("cc-by-nc-sa", "CC BY-NC-SA — Attribution-NonCommercial-ShareAlike"),
                    ("cc-by-nc-nd", "CC BY-NC-ND — Attribution-NonCommercial-NoDerivatives"),
                    ("all-rights-reserved", "All Rights Reserved"),
                ],
                default="cc0",
                help_text="Default license applied to new sightings and media",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="default_license",
            field=models.CharField(
                choices=[
                    ("cc0", "CC0 — Public Domain Dedication"),
                    ("cc-by", "CC BY — Attribution"),
                    ("cc-by-sa", "CC BY-SA — Attribution-ShareAlike"),
                    ("cc-by-nd", "CC BY-ND — Attribution-NoDerivatives"),
                    ("cc-by-nc", "CC BY-NC — Attribution-NonCommercial"),
                    ("cc-by-nc-sa", "CC BY-NC-SA — Attribution-NonCommercial-ShareAlike"),
                    ("cc-by-nc-nd", "CC BY-NC-ND — Attribution-NonCommercial-NoDerivatives"),
                    ("all-rights-reserved", "All Rights Reserved"),
                ],
                default="cc0",
                help_text="Default license applied to new sightings and media",
                max_length=32,
            ),
        ),
    ]
