# Generated by Django 5.0.2 on 2026-04-05 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_default_license_db_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='default_license',
            field=models.CharField(choices=[('cc0', 'CC0 — Public Domain Dedication'), ('cc-by', 'CC BY — Attribution'), ('cc-by-sa', 'CC BY-SA — Attribution-ShareAlike'), ('cc-by-nd', 'CC BY-ND — Attribution-NoDerivatives'), ('cc-by-nc', 'CC BY-NC — Attribution-NonCommercial'), ('cc-by-nc-sa', 'CC BY-NC-SA — Attribution-NonCommercial-ShareAlike'), ('cc-by-nc-nd', 'CC BY-NC-ND — Attribution-NonCommercial-NoDerivatives'), ('all-rights-reserved', 'All Rights Reserved')], db_default='cc0', default='cc0', help_text='Default license applied to new sightings and media', max_length=32),
        ),
        migrations.CreateModel(
            name='UserAPIKey',
            fields=[
                ('id', models.CharField(editable=False, max_length=150, primary_key=True, serialize=False, unique=True)),
                ('prefix', models.CharField(editable=False, max_length=8, unique=True)),
                ('hashed_key', models.CharField(editable=False, max_length=150)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('name', models.CharField(default=None, help_text='A free-form name for the API key. Need not be unique. 50 characters max.', max_length=50)),
                ('revoked', models.BooleanField(blank=True, default=False, help_text='If the API key is revoked, clients cannot use it anymore. (This cannot be undone.)')),
                ('expiry_date', models.DateTimeField(blank=True, help_text='Once API key expires, clients cannot use it anymore.', null=True, verbose_name='Expires')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User API Key',
                'verbose_name_plural': 'User API Keys',
                'ordering': ('-created',),
                'abstract': False,
            },
        ),
    ]
