# Generated by Django 5.0.2 on 2026-04-05 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_add_user_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='is_developer',
            field=models.BooleanField(default=False, help_text='Grants developer/API access. Staff and superusers are automatically considered developers.'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_developer',
            field=models.BooleanField(default=False, help_text='Grants developer/API access. Staff and superusers are automatically considered developers.'),
        ),
    ]
