"""
Django settings for wilde_backyard project.

Generated by 'django-admin startproject' using Django 4.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

import os
from pathlib import Path

import environ

# Repo root
ROOT_URLCONF = "config.urls"
ROOT_DIR = Path(__file__).resolve(strict=True).parent.parent.parent
# siteapps/
APPS_DIR = ROOT_DIR / "siteapps"

env = environ.Env(DEBUG=(bool, False))
# Local environment file path
env_file = ROOT_DIR / ".env"

LOGIN_URL = "/users/login"

# URL of the web frontend — used to redirect users after email confirmation
WEB_APP_URL = env.str("WEB_APP_URL", default="http://localhost:8001")
ACCOUNT_EMAIL_CONFIRMATION_ANONYMOUS_REDIRECT_URL = f"{WEB_APP_URL}/users/login/"
ACCOUNT_EMAIL_CONFIRMATION_AUTHENTICATED_REDIRECT_URL = f"{WEB_APP_URL}/users/profile/"


# Secrets

# To store read secrets (for backward compatibility with existing code)
SECRETS = {}

if env_file.is_file():
    env.read_env(env_file)


# GENERAL
# ------------------------------------------------------------------------------
# https://docs.djangoproject.com/en/dev/ref/settings/#secret-key
SECRET_KEY = env.str(
    "DJANGO_SECRET_KEY", default=SECRETS.get("DJANGO-SECRET-KEY", "test-secret-key-change-in-production")
)
# DEBUG MODE
DEBUG = False

# HOSTS CONFIG
# ------------------------------------------------------------------------------
# Allow disabling ALLOWED_HOSTS check for non-production deployments
# Set DISABLE_ALLOWED_HOSTS_CHECK=true in environment to disable host validation
# WARNING: Only use this in non-production environments
DISABLE_ALLOWED_HOSTS_CHECK = env.bool("DISABLE_ALLOWED_HOSTS_CHECK", default=False)
if DISABLE_ALLOWED_HOSTS_CHECK:
    ALLOWED_HOSTS = ["*"]
else:
    ALLOWED_HOSTS = []
# Local time zone. Choices are
# http://en.wikipedia.org/wiki/List_of_tz_zones_by_name
# though not all of them may be available with every OS.
# In Windows, this must be set to your system time zone.
# https://docs.djangoproject.com/en/dev/ref/settings/#language-code
LANGUAGE_CODE = "en-us"
# https://docs.djangoproject.com/en/dev/ref/settings/#site-id
SITE_ID = 1
# https://docs.djangoproject.com/en/dev/ref/settings/#use-i18n
USE_I18N = True
# https://docs.djangoproject.com/en/dev/ref/settings/#use-l10n
USE_L10N = True
# https://docs.djangoproject.com/en/dev/ref/settings/#use-tz
USE_TZ = False


# Application definition

INSTALLED_APPS = [
    "corsheaders",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.gis",
    "rest_framework",
    "rest_framework.authtoken",
    "drf_spectacular",
    "dj_rest_auth",
    "dj_rest_auth.registration",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.openid",
    "django_rest_passwordreset",
    "siteapps.users",
    "siteapps.socialmedia",
    "siteapps.species",
    "siteapps.mapbox",
]

MIDDLEWARE = [
    "config.middleware.BufferRequestMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "allauth.account.middleware.AccountMiddleware",
]

AUTH_USER_MODEL = "users.User"

ROOT_URLCONF = "config.urls"


DJANGO_REST_PASSWORDRESET_TOKEN_CONFIG = {
    "CLASS": "django_rest_passwordreset.tokens.RandomNumberTokenGenerator",
    "OPTIONS": {
        "min_number": 1000000,
        "max_number": 9999999,
    },
}


TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            os.path.join(ROOT_DIR, "siteapps/templates"),
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.template.context_processors.i18n",
                "django.template.context_processors.media",
                "django.template.context_processors.static",
                "django.template.context_processors.tz",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": ROOT_DIR / "db.sqlite3",
    }
}


REST_FRAMEWORK = {
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 10,
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}

# drf-spectacular settings
SPECTACULAR_SETTINGS = {
    "TITLE": "Wilde Backyard API",
    "DESCRIPTION": "REST API for Wilde Backyard wildlife social media platform",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "COMPONENT_SPLIT_REQUEST": True,
}

# Limit data upload size to 700 MB to accommodate base64-encoded videos
# (500MB video * 1.33 base64 overhead = ~665MB)
DATA_UPLOAD_MAX_MEMORY_SIZE = 734003200  # 700 MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 734003200  # 700 MB

# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# STATIC
# ------------------------------------------------------------------------------
# https://docs.djangoproject.com/en/dev/ref/settings/#static-url
STATIC_URL = "/static/"
# https://docs.djangoproject.com/en/dev/ref/settings/#static-root
STATIC_ROOT = str(ROOT_DIR / "staticfiles")
# https://docs.djangoproject.com/en/dev/ref/contrib/staticfiles/#std:setting-STATICFILES_DIRS
STATICFILES_DIRS = [str(APPS_DIR / "static")]
# https://docs.djangoproject.com/en/dev/ref/contrib/staticfiles/#staticfiles-finders
STATICFILES_FINDERS = [
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
]
# WhiteNoise will handle all static files
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# django-allauth
# ------------------------------------------------------------------------------
ACCOUNT_ALLOW_REGISTRATION = env.bool("DJANGO_ACCOUNT_ALLOW_REGISTRATION", False)
# https://django-allauth.readthedocs.io/en/latest/configuration.html
ACCOUNT_AUTHENTICATION_METHOD = "email"
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_EMAIL_VERIFICATION = "mandatory"
ACCOUNT_ADAPTER = "siteapps.users.adapters.AccountAdapter"
ACCOUNT_USER_MODEL_USERNAME_FIELD = None
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_CONFIRM_EMAIL_ON_GET = True
ACCOUNT_MAX_EMAIL_ADDRESSES = 2
ACCOUNT_LOGIN_ON_PASSWORD_RESET = True
ACCOUNT_LOGOUT_ON_PASSWORD_CHANGE = True
ACCOUNT_SESSION_REMEMBER = True
# https://django-allauth.readthedocs.io/en/latest/forms.html


# dj-rest-auth
# ------------------------------------------------------------------------------
REST_AUTH = {
    "REGISTER_SERIALIZER": "siteapps.users.serializers.RegisterSerializer",
}


# PASSWORDS
# ------------------------------------------------------------------------------
# https://docs.djangoproject.com/en/dev/ref/settings/#password-hashers
PASSWORD_HASHERS = [
    # https://docs.djangoproject.com/en/dev/topics/auth/passwords/#using-argon2-with-django
    "django.contrib.auth.hashers.Argon2PasswordHasher",
    "django.contrib.auth.hashers.PBKDF2PasswordHasher",
    "django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher",
    "django.contrib.auth.hashers.BCryptSHA256PasswordHasher",
]
# https://docs.djangoproject.com/en/dev/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]


# EMAIL
# ------------------------------------------------------------------------------
# https://docs.djangoproject.com/en/dev/ref/settings/#default-from-email
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"

DEFAULT_FROM_EMAIL = env(
    "DJANGO_DEFAULT_FROM_EMAIL",
    default="Admin <noreply@wildepod.org>",
)
# https://docs.djangoproject.com/en/dev/ref/settings/#server-email
SERVER_EMAIL = env("DJANGO_SERVER_EMAIL", default=DEFAULT_FROM_EMAIL)
# https://docs.djangoproject.com/en/dev/ref/settings/#email-subject-prefix
EMAIL_SUBJECT_PREFIX = "[Wilde Backyard]"
ACCOUNT_EMAIL_SUBJECT_PREFIX = ""

# Mailgun SMTP settings
EMAIL_HOST = "smtp.mailgun.org"
EMAIL_HOST_USER = "noreply@wildepod.org"
EMAIL_HOST_PASSWORD = env.str("MAILGUN_SMTP_PASSWORD", default="")
EMAIL_PORT = 587
EMAIL_USE_TLS = True

# Mapbox (optional)
MAPBOX_SECRET_TOKEN = env.str("MAPBOX_SECRET_TOKEN", default=SECRETS.get("MAPBOX-SECRET-TOKEN", None))


# CUSTOM VARIABLES
# ------------------------------------------------------------------------------
# Put your variables here.
PRIVACY_SETTING_PUBLIC = "public"
PRIVACY_SETTING_OBSCURED = "obscured"
PRIVACY_SETTING_PRIVATE = "private"

PHOTO_MAX_SIZE = (2048, 2048)
# Maximum video file size in megabytes
MAX_VIDEO_SIZE_MB = 500

READABLE_DATE_FORMAT = "%B %d, %Y %I:%M %p"

# Google Cloud Storage settings
GCS_BUCKET_NAME = env.str("GCS_BUCKET_NAME", SECRETS.get("GCS-BUCKET-NAME", "wildepod_backyard"))
# Path within GCS bucket for storing images
GCS_IMAGES_PATH = "media/images"
# Path within GCS bucket for storing videos (movies is used for consistency with existing naming)
GCS_VIDEOS_PATH = "media/movies"
