runtime: python310
service: wildebackyard-api
instance_class: F2
entrypoint: gunicorn -t 2400 -b :$PORT config.wsgi.wildebackyard_api:application

env_variables:
  DJANGO_SETTINGS_MODULE: "config.settings.wildebackyard_api"
  PYTHON_ENV: "production"
  CLOUD_SQL_CONNECTION_NAME: "wildepod-339517:us-west2:wildepoddb"
  WILDEBACKYARD_API_DATABASE_URL: "postgres://wildepod_wildebackyard_api_user:CLEANED_PASSWORD@/wildebackyard_api_staging?host=/cloudsql/wildepod-339517:us-west2:wildepoddb"

automatic_scaling:
  min_idle_instances: 0
  max_idle_instances: 2
  min_pending_latency: 1000ms
  max_pending_latency: 3000ms
  max_concurrent_requests: 50
